fixed missing return value
JetBrains/phpstorm-stubs pull request #1151
Opened 2021-06-16 07:59 UTC by brainfoolong

JsonSerializable::jsonSerialize is defined to have "mixed" as return type, will throw errors in php 8.1 if you not correctly define that return type
Error in php 8.1 example: `Declaration of xxx::jsonSerialize() should be compatible with xxx::jsonSerialize(): mixed`

2021-06-18 10:25 UTC, isfedorov commented
@brainfoolong while your fix is correct for PHP 8-8.1 it's wrong for PHP < 8 as far as mixed typehint was introduced in PHP 8 and thus overriding this method in PHP < 8 will produce false positive warnings. To avoid this please use #[LanguageLevelTypeAware] attribute like 
```
#[LanguageLevelTypeAware(['8.1'=>'mixed'], default: '')]
public function jsonSerialize();
```

2021-06-20 11:18 UTC, brainfoolong commented
Thanks for the hint. Changed it.

2021-06-20 12:26 UTC, isfedorov requested changes

2021-06-20 12:26 UTC, isfedorov commented on json/json.php
> +    #[LanguageLevelTypeAware(['8.1'=>'mixed'], default: '')]
Please also add class `LanguageLevelTypeAware` to imports and perform `docker-compose -f docker-compose.yml run php composer cs-fix -d /opt/project/phpstorm-stubs` to fix code-style related problems

2021-06-20 12:28 UTC, brainfoolong commented
Sorry, i don't have a full blown development environment for this stubs. I can't fix more than this, it was a quick change with just a texteditor. Should i close this when i can't resolve it properly?

2021-07-21 10:27 UTC, isfedorov commented
Fixed in other PR

2021-07-21 10:27 UTC, closed without merging