Update fwrite return type to include 'false'
JetBrains/phpstorm-stubs pull request #1169
Opened 2021-07-11 07:56 UTC by martin-juul

Since 7.4.0 SplFileObject::fwrite returns false instead of 0 on failure

[PHP Manual Reference](https://www.php.net/manual/en/splfileobject.fwrite.php)

2021-07-11 13:15 UTC, voku commented
Maybe "int|false" would be more correct.

2021-07-11 19:00 UTC, isfedorov requested changes

2021-07-11 19:00 UTC, isfedorov commented on SPL/SPL_c1.php
>           */
@martin-juul Please use #[LanguageLevelTypeAware] attribute to set return types different for different PHP versions. You can find examples of usages of attribute across stubs.

2021-07-21 08:12 UTC, isfedorov commented
Fixed in a separate PR

2021-07-21 08:12 UTC, closed without merging