Add missing allocate, capacity, pop for DS\PriorityQueue
JetBrains/phpstorm-stubs pull request #1430
Opened 2022-08-16 00:40 UTC by tfedor

2022-08-16 17:07 UTC, DmitryTronin requested changes
Also please update your project & push again to include the recent constants changes: https://github.com/JetBrains/phpstorm-stubs/pull/1431

2022-08-16 17:07 UTC, DmitryTronin commented on ds/ds.php
> +
Please run php-cs-fixer as described in readme to reformat the code. Or just remove whitespaces here, per failed tests: https://github.com/JetBrains/phpstorm-stubs/pull/1430/checks#step:5:8

2022-09-08 10:49 UTC, DmitryTronin commented
Hi @tfedor. Could you please address the changes requested here if you have spare time?

2022-09-08 21:58 UTC, tfedor commented
@DmitryTronin sorry for delay, should be fixed now

2022-09-21 10:52 UTC, merged