Add stubs for Relay
JetBrains/phpstorm-stubs pull request #1514
Opened 2023-01-12 23:37 UTC by tillkruss

2023-01-12 23:48 UTC, tillkruss commented
@isfedorov: Could you give me pointers what's needed to get these stubs merged?

2023-01-15 21:46 UTC, isfedorov commented
@tillkruss do you have any statistics about the current usage of the Relay extension? The extension looks like a very early build (based on 0.X version, amount of commits, forks, stars, etc) so sorry, but at the moment I don't see any guarantee that the work on the extension will continue. Unfortunately, we can't bundle stubs for every extension and would like to align with stubs for the extensions that are going to live for a while and are used by a significant amount of people. So could you please provide some data on usage the extension (monthly installs, summary installs etc)?

2023-01-16 16:53 UTC, tillkruss commented
@isfedorov You're absolutely right, it's early days and we've only soft launched, but 3 people are working full time on Relay and just over 10k active (production) installations right now. Those are early adopters in the WordPress hosting space.

It would be great to get this merged, since Laravel and Symfony both are adding support for it.

Are those numbers sufficient, or do you have any specific usage requirements?

2023-01-26 19:05 UTC, isfedorov requested changes
Please remove `@return` tag from constructors as they look completely redundant. 
Please replace `@alias` tags with the supported tag. 
Please update stubs map https://github.com/JetBrains/phpstorm-stubs#how-to-update-stub-map
Please add `relay` to `\StubTests\TestData\Providers\Stubs\PhpCoreStubsProvider::$StubDirectoryMap` to `OTHERS` array

2023-01-26 19:06 UTC, isfedorov commented
@tillkruss Ok, lets bundle them. But before that the PR requires some changes (please see my notes)

2023-01-26 19:13 UTC, szepeviktor commented on relay/Relay.php
> +     * @return Relay
Constructor return types should not be written anywhere.

2023-01-26 19:24 UTC, tillkruss commented on relay/Relay.php
> +     * @return Relay
Thanks, will remove.

2023-01-26 19:39 UTC, tillkruss commented on relay/Relay.php
> +     * @alias Relay\Relay::getReadTimeout
I see. PHP src actually uses the `@alias` tag for linking methods. Will replace here.

2023-01-26 20:03 UTC, tillkruss commented
@isfedorov: All done. Happy to do the `LanguageLevelTypeAware` stuff if needed.

2023-01-26 21:20 UTC, isfedorov commented
@tillkruss Ok, so the only problem left is cs-fixer problems. Please run cs-fixer as mentioned at https://github.com/JetBrains/phpstorm-stubs/blob/master/CONTRIBUTING.md#code-style

2023-01-26 21:31 UTC, tillkruss commented
Done 👍

2023-01-30 18:43 UTC, szepeviktor approved these changes

2023-01-30 21:37 UTC, merged