WI-73896: Fix T_BAD_CHARACTER annotation
JetBrains/phpstorm-stubs pull request #1563
Opened 2023-08-12 15:14 UTC by lkrms

2023-08-16 15:36 UTC, LolGleb commented
Could you please completely remove the PHPDoc? `T_BAD_CHARACTER` token previously already existed in PHP, but was removed in PHP 7.0. After that it was reintroduced in PHP 7.4. So saying that it is only available since 7.4 not entirely correct.

2023-08-17 13:05 UTC, LolGleb requested changes

2023-08-17 13:05 UTC, LolGleb commented on tokenizer/tokenizer.php
> + * @since 7.4
Please, remove the PHPDoc completely

2023-08-23 12:27 UTC, lkrms commented
Apologies for the delay, I've made the requested change and rebased.

2023-08-23 12:45 UTC, merged