Fix yaf stubs
JetBrains/phpstorm-stubs pull request #1610
Opened 2024-01-24 10:46 UTC by mbakirov

This PR contain fixes for YAF stubs against https://github.com/laruence/yaf/ repo

2024-02-06 14:01 UTC, isfedorov requested changes

2024-02-13 22:14 UTC, isfedorov requested changes

2024-02-13 22:14 UTC, isfedorov commented on yaf/yaf.php
> + * @implements \Iterator<mixed,mixed>
Please remove <mixed, mixed> since it doesn't make sense

2024-03-13 10:55 UTC, mbakirov commented
@isfedorov thank you for your comments! I've fixed them all

2024-04-02 14:17 UTC, mbakirov commented
@isfedorov may I ask your review please?

2024-04-02 15:08 UTC, isfedorov requested changes
@mbakirov  Sorry for the long review. Looks like it's only a couple of final notes left. Could you please take a look at them and we will merge PR after that.

2024-04-03 09:25 UTC, mbakirov commented
@isfedorov I have removed all `@implements` phpdoc comments

2024-04-03 21:27 UTC, merged